package com.example.currencyconverter

object CurrencyData {
    fun getAllCurrencies(): List<Currency> {
        return listOf(
            Currency("Afghanistan", "Afghani", "AFN", 87.5),
            Currency("Albania", "Lek", "ALL", 106.0),
            Currency("Algeria", "Dinar", "DZD", 135.0),
            Currency("Argentina", "Peso", "ARS", 250.0),
            Currency("Armenia", "Dram", "AMD", 400.0),
            Currency("Australia", "Australian Dollar", "AUD", 1.4),
            Currency("Austria", "Euro", "EUR", 1.0),
            Currency("Azerbaijan", "Azerbaijani Manat", "AZN", 1.7),
            Currency("Bahamas", "Bahamian Dollar", "BSD", 1.0),
            Currency("Bahrain", "Bahraini Dinar", "BHD", 0.38),
            Currency("Bangladesh", "Taka", "BDT", 100.0),
            Currency("Barbados", "Barbadian Dollar", "BBD", 2.0),
            Currency("Belarus", "Belarusian Ruble", "BYN", 2.6),
            Currency("Belgium", "Euro", "EUR", 1.0),
            Currency("Belize", "Belize Dollar", "BZD", 2.0),
            Currency("Benin", "West African CFA Franc", "XOF", 600.0),
            Currency("Bhutan", "Ngultrum", "BTN", 80.0),
            Currency("Bolivia", "Boliviano", "BOB", 6.9),
            Currency("Bosnia and Herzegovina", "Convertible Mark", "BAM", 1.9),
            Currency("Botswana", "Pula", "BWP", 13.0),
            Currency("Brazil", "Brazilian Real", "BRL", 5.2),
            Currency("Brunei", "Brunei Dollar", "BND", 1.4),
            Currency("Bulgaria", "Bulgarian Lev", "BGN", 1.9),
            Currency("Burkina Faso", "West African CFA Franc", "XOF", 600.0),
            Currency("Burundi", "Burundian Franc", "BIF", 2000.0),
            Currency("Cabo Verde", "Cabo Verdean Escudo", "CVE", 100.0),
            Currency("Cambodia", "Riel", "KHR", 4100.0),
            Currency("Cameroon", "Central African CFA Franc", "XAF", 600.0),
            Currency("Canada", "Canadian Dollar", "CAD", 1.3),
            Currency("Central African Republic", "Central African CFA Franc", "XAF", 600.0),
            Currency("Chile", "Chilean Peso", "CLP", 800.0),
            Currency("China", "Renminbi", "CNY", 6.5),
            Currency("Colombia", "Colombian Peso", "COP", 4000.0),
            Currency("Costa Rica", "Costa Rican Colón", "CRC", 540.0),
            Currency("Croatia", "Croatian Kuna", "HRK", 7.5),
            Currency("Cyprus", "Euro", "EUR", 1.0),
            Currency("Czech Republic", "Czech Koruna", "CZK", 22.0),
            Currency("Democratic Republic of the Congo", "Congolese Franc", "CDF", 2000.0),
            Currency("Denmark", "Danish Krone", "DKK", 7.0),
            Currency("Djibouti", "Djiboutian Franc", "DJF", 177.0),
            Currency("Dominican Republic", "Dominican Peso", "DOP", 56.0),
            Currency("Ecuador", "United States Dollar", "USD", 1.0),
            Currency("Egypt", "Egyptian Pound", "EGP", 30.0),
            Currency("El Salvador", "United States Dollar", "USD", 1.0),
            Currency("Equatorial Guinea", "Central African CFA Franc", "XAF", 600.0),
            Currency("Estonia", "Euro", "EUR", 1.0),
            Currency("Eswatini", "Lilangeni", "SZL", 18.0),
            Currency("Ethiopia", "Birr", "ETB", 55.0),
            Currency("Fiji", "Fijian Dollar", "FJD", 2.2),
            Currency("Finland", "Euro", "EUR", 1.0),
            Currency("France", "Euro", "EUR", 1.0),
            Currency("Gabon", "Central African CFA Franc", "XAF", 600.0),
            Currency("Georgia", "Lari", "GEL", 3.7),
            Currency("Germany", "Euro", "EUR", 1.0),
            Currency("Ghana", "Ghanaian Cedi", "GHS", 12.0),
            Currency("Greece", "Euro", "EUR", 1.0),
            Currency("Grenada", "East Caribbean Dollar", "XCD", 2.7),
            Currency("Guatemala", "Quetzal", "GTQ", 7.7),
            Currency("Guinea", "Guinean Franc", "GNF", 9000.0),
            Currency("Guinea-Bissau", "West African CFA Franc", "XOF", 600.0),
            Currency("Guyana", "Guyanese Dollar", "GYD", 210.0),
            Currency("Haiti", "Gourde", "HTG", 150.0),
            Currency("Honduras", "Lempira", "HNL", 24.0),
            Currency("Hungary", "Forint", "HUF", 400.0),
            Currency("Iceland", "Icelandic Króna", "ISK", 140.0),
            Currency("India", "Indian Rupee", "INR", 80.0),
            Currency("Indonesia", "Rupiah", "IDR", 15000.0),
            Currency("Iran", "Iranian Rial", "IRR", 42000.0),
            Currency("Iraq", "Iraqi Dinar", "IQD", 1450.0),
            Currency("Ireland", "Euro", "EUR", 1.0),
            Currency("Israel", "Israeli New Shekel", "ILS", 3.5),
            Currency("Italy", "Euro", "EUR", 1.0),
            Currency("Jamaica", "Jamaican Dollar", "JMD", 150.0),
            Currency("Japan", "Yen", "JPY", 110.0),
            Currency("Jordan", "Jordanian Dinar", "JOD", 0.71),
            Currency("Kazakhstan", "Tenge", "KZT", 450.0),
            Currency("Kenya", "Kenyan Shilling", "KES", 150.0),
            Currency("Kiribati", "Australian Dollar", "AUD", 1.4),
            Currency("Kuwait", "Kuwaiti Dinar", "KWD", 0.31),
            Currency("Kyrgyzstan", "Som", "KGS", 85.0),
            Currency("Laos", "Kip", "LAK", 8800.0),
            Currency("Latvia", "Euro", "EUR", 1.0),
            Currency("Lebanon", "Lebanese Pound", "LBP", 30000.0),
            Currency("Lesotho", "Loti", "LSL", 18.0),
            Currency("Liberia", "Liberian Dollar", "LRD", 150.0),
            Currency("Libya", "Libyan Dinar", "LYD", 4.5),
            Currency("Liechtenstein", "Swiss Franc", "CHF", 0.9),
            Currency("Lithuania", "Euro", "EUR", 1.0),
            Currency("Luxembourg", "Euro", "EUR", 1.0),
            Currency("Madagascar", "Ariary", "MGA", 4100.0),
            Currency("Malawi", "Kwacha", "MWK", 1000.0),
            Currency("Malaysia", "Ringgit", "MYR", 4.5),
            Currency("Maldives", "Rufiyaa", "MVR", 15.0),
            Currency("Mali", "West African CFA Franc", "XOF", 600.0),
            Currency("Malta", "Euro", "EUR", 1.0),
            Currency("Marshall Islands", "United States Dollar", "USD", 1.0),
            Currency("Mauritania", "Ouguiya", "MRU", 380.0),
            Currency("Mauritius", "Mauritian Rupee", "MUR", 44.0),
            Currency("Mexico", "Mexican Peso", "MXN", 18.0),
            Currency("Micronesia", "United States Dollar", "USD", 1.0),
            Currency("Moldova", "Moldovan Leu", "MDL", 17.0),
            Currency("Monaco", "Euro", "EUR", 1.0),
            Currency("Mongolia", "Tögrög", "MNT", 3500.0),
            Currency("Montenegro", "Euro", "EUR", 1.0),
            Currency("Morocco", "Moroccan Dirham", "MAD", 10.0),
            Currency("Mozambique", "Metical", "MZN", 60.0),
            Currency("Namibia", "Namibian Dollar", "NAD", 18.0),
            Currency("Nauru", "Australian Dollar", "AUD", 1.4),
            Currency("Nepal", "Nepalese Rupee", "NPR", 130.0),
            Currency("Netherlands", "Euro", "EUR", 1.0),
            Currency("New Zealand", "New Zealand Dollar", "NZD", 1.5),
            Currency("Nicaragua", "Córdoba", "NIO", 36.0),
            Currency("Niger", "West African CFA Franc", "XOF", 600.0),
            Currency("Nigeria", "Naira", "NGN", 700.0),
            Currency("North Macedonia", "Denar", "MKD", 60.0),
            Currency("Norway", "Norwegian Krone", "NOK", 9.5),
            Currency("Oman", "Rial", "OMR", 0.38),
            Currency("Pakistan", "Pakistani Rupee", "PKR", 280.0),
            Currency("Palau", "United States Dollar", "USD", 1.0),
            Currency("Panama", "Balboa", "PAB", 1.0),
            Currency("Papua New Guinea", "Papua New Guinean Kina", "PGK", 3.5),
            Currency("Paraguay", "Guaraní", "PYG", 7000.0),
            Currency("Peru", "Peruvian Sol", "PEN", 3.7),
            Currency("Philippines", "Philippine Peso", "PHP", 55.0),
            Currency("Poland", "Złoty", "PLN", 4.5),
            Currency("Portugal", "Euro", "EUR", 1.0),
            Currency("Qatar", "Qatari Rial", "QAR", 3.6),
            Currency("Romania", "Romanian Leu", "RON", 4.5),
            Currency("Russia", "Russian Ruble", "RUB", 100.0),
            Currency("Saudi Arabia", "Saudi Riyal", "SAR", 3.75),
            Currency("Singapore", "Singapore Dollar", "SGD", 1.4),
            Currency("South Africa", "South African Rand", "ZAR", 18.0),
            Currency("South Korea", "Won", "KRW", 1300.0),
            Currency("Spain", "Euro", "EUR", 1.0),
            Currency("Sri Lanka", "Sri Lankan Rupee", "LKR", 280.0),
            Currency("Sweden", "Swedish Krona", "SEK", 10.0),
            Currency("Switzerland", "Swiss Franc", "CHF", 0.9),
            Currency("Syria", "Syrian Pound", "SYP", 13000.0),
            Currency("Taiwan", "New Taiwan Dollar", "TWD", 30.0),
            Currency("Tanzania", "Tanzanian Shilling", "TZS", 2300.0),
            Currency("Tunisia", "Tunisian Dinar", "TND", 3.0),
            Currency("Turkey", "Turkish Lira", "TRY", 27.0),
            Currency("Ukraine", "Hryvnia", "UAH", 36.0),
            Currency("United Arab Emirates", "UAE Dirham", "AED", 3.67),
            Currency("United Kingdom", "British Pound", "GBP", 0.8),
            Currency("United States", "United States Dollar", "USD", 1.0),
            Currency("Uzbekistan", "Som", "UZS", 11000.0),
            Currency("Venezuela", "Bolívar", "VES", 3000.0),
            Currency("Vietnam", "Vietnamese Dong", "VND", 23000.0)
        )
    }
}
